import type { Property } from "./types";

export const properties: Property[] = [
  {
    id: "1",
    code: "HN-000184",
    slug: "casa-moderna-residencial-el-hatillo-hn-184",
    title: "Casa moderna en Residencial El Hatillo",
    operation: "SALE",
    type: "Casa",
    price: 6850000,
    currency: "HNL",
    city: "Tegucigalpa",
    department: "Francisco Morazán",
    bedrooms: 4,
    bathrooms: 3.5,
    parking: 2,
    constructionAreaM2: 320,
    landAreaM2: 550,
    featuredLabel: "Destacada",
    image: "https://images.unsplash.com/photo-1600585154340-be6161a56a0c?auto=format&fit=crop&w=1600&q=80",
    summary: "Residencia contemporánea, amplia y luminosa, ideal para familia o inversión patrimonial.",
  },
  {
    id: "2",
    code: "HN-000211",
    slug: "apartamento-premium-san-pedro-sula-hn-211",
    title: "Apartamento premium en Torre Astria",
    operation: "SALE",
    type: "Apartamento",
    price: 4200000,
    currency: "HNL",
    city: "San Pedro Sula",
    department: "Cortés",
    bedrooms: 3,
    bathrooms: 2,
    parking: 2,
    constructionAreaM2: 180,
    featuredLabel: "Nueva",
    image: "https://images.unsplash.com/photo-1545324418-cc1a3fa10c00?auto=format&fit=crop&w=1600&q=80",
    summary: "Apartamento urbano con amenidades, seguridad y excelente conectividad.",
  },
  {
    id: "3",
    code: "HN-000239",
    slug: "terreno-valle-de-angeles-hn-239",
    title: "Terreno en Valle de Ángeles",
    operation: "SALE",
    type: "Terreno",
    price: 1850000,
    currency: "HNL",
    city: "Valle de Ángeles",
    department: "Francisco Morazán",
    landAreaM2: 1200,
    featuredLabel: "Oportunidad",
    image: "https://images.unsplash.com/photo-1500530855697-b586d89ba3ee?auto=format&fit=crop&w=1600&q=80",
    summary: "Terreno con entorno natural, acceso vehicular y potencial residencial.",
  },
  {
    id: "4",
    code: "HN-000247",
    slug: "local-comercial-san-pedro-sula-hn-247",
    title: "Local comercial en zona estratégica",
    operation: "RENT",
    type: "Local comercial",
    price: 45000,
    currency: "HNL",
    city: "San Pedro Sula",
    department: "Cortés",
    parking: 4,
    constructionAreaM2: 120,
    featuredLabel: "Comercial",
    image: "https://images.unsplash.com/photo-1497366754035-f200968a6e72?auto=format&fit=crop&w=1600&q=80",
    summary: "Local con alta visibilidad, estacionamiento y ubicación comercial consolidada.",
  },
];
